#ifndef STRESS_CONFIG_H
#define STRESS_CONFIG_H

#include <stdint.h>

#define STRESS_CAPACITY_CONNECTIONS 500u
#define STRESS_CEILING_CONNECTIONS 600u
#define STRESS_CEILING_STEP 10u
#define STRESS_CAPACITY_HOLD_SECONDS 10u
#define STRESS_THROUGHPUT_REPETITIONS 3u
#define STRESS_THROUGHPUT_BYTES (64ull * 1024ull * 1024ull)
#define STRESS_CHUNK_SIZE (16u * 1024u)
#define STRESS_CAPACITY_PAYLOAD 1024u
#define STRESS_SOAK_SECONDS 60u
#define STRESS_SOAK_PAYLOAD 1024u
#define STRESS_HANDSHAKE_TIMEOUT_SECONDS 30u
#define STRESS_RUN_TIMEOUT_SECONDS 180u
#define STRESS_CLEANUP_TIMEOUT_SECONDS 5u
#define STRESS_POLL_INTERVAL_MS 100

#define STRESS_PROXY_USER "stress"
#define STRESS_PROXY_PASS "stress-pass"
#define STRESS_ADMIN_USER "stress-admin"
#define STRESS_ADMIN_PASS "stress-admin-pass"

static const unsigned STRESS_THROUGHPUT_LEVELS[] = {1u, 50u, 100u, 250u, 500u};
#define STRESS_THROUGHPUT_LEVEL_COUNT \
    (sizeof(STRESS_THROUGHPUT_LEVELS) / sizeof(STRESS_THROUGHPUT_LEVELS[0]))

#endif
